sudo: required
services:
    - docker

before_install:
  - docker build -t karpin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true karpin/react-test npm test

after_success:
  - docker build -t karpin/multi-client ./client
  - docker build -t karpin/multi-nginx ./nginx
  - docker build -t karpin/multi-server ./server
  - docker build -t karpin/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub