sudo: required
services:
    - docker

before_install:
  - docker build -t karpin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true karpin/react-test npm test

after_success:
  - docker build -t karpin/multi-client ./client
  - docker build -t karpin/multi-nginx ./nginx
  - docker build -t karpin/multi-server ./server
  - docker build -t karpin/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push karpin/multi-client
  - docker push karpin/multi-nginx
  - docker push karpin/multi-server
  - docker push karpin/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucker_name: elasticbeanstalk-us-east-2-556463984563
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
